name: dinov2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu117
    - --extra-index-url https://pypi.nvidia.com
    - torch==2.0.0
    - torchvision==0.15.1
    - xformers==0.0.18
    - omegaconf
    - torchmetrics==0.10.3
    - fvcore
    - iopath
    - cuml-cu11
    - git+https://github.com/facebookincubator/submitit