name: dinov2
channels:
  - defaults
  - pytorch
  - nvidia
  - xformers
  - conda-forge
dependencies:
  - python=3.10
  - pytorch::pytorch=2.0.0
  - pytorch::pytorch-cuda=11.7.0
  - pytorch::torchvision=0.15.0
  - omegaconf
  - torchmetrics=0.10.3
  - fvcore
  - iopath
  - xformers::xformers=0.0.18
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu117
    - git+https://github.com/facebookincubator/submitit
    - --extra-index-url https://pypi.nvidia.com
    - cuml-cu11
    - torch==2.0.0
    - torchvision==0.15.1
    - xformers==0.0.18
    - omegaconf
    - torchmetrics==0.10.3
    - fvcore
    - iopath
    - cuml-cu11
    - git+https://github.com/facebookincubator/submitit